name: Lobbysystem
version: '2.0.0-FOLIA'
main: de.devsnx.xaldrion.lobbysystem.Lobbysystem
api-version: '1.20'
author: DevSnx

depend:
  - Folia

# Add this line to specify Folia support
softdepend: [Folia]